---
baseURL: "https://docs.operaton.org"
languageCode: "en-us"
title: "Operaton documentation"
theme: "operaton"

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: ""
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Operaton"
      url: "/manual"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "manual"
    version: "latest"
    versionAlias: "1.0.0-beta-2"
    versions:
      - "latest"
      - "1.0.0-beta-1"
      - "1.0.0-beta-2"
  github:
    repositoryName: "operaton/docs-operaton-org"
    branch: "main"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true

disableKinds:
- taxonomy
...
